name: Beta release

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'force release even if no update(set empty if not)'
        required: false
        default: '--force-publish'
      stable:
        description: 'promote to stable version(true or false)'
        required: false
        default: 'false'

jobs:
  release-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CD_PAT }}
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: Download Simple Auth bits
        env:
          SIMPLE_AUTH_SAS_TOKEN: ${{secrets.SIMPLE_AUTH_SAS_TOKEN}}
          SIMPLE_AUTH_ENDPOINT: ${{secrets.SIMPLE_AUTH_ENDPOINT}}
        run: |
            $version=Get-Content packages/fx-core/templates/plugins/resource/simpleauth/version.txt
            $fileName="Microsoft.TeamsFx.SimpleAuth_$version.zip"
            echo $SIMPLE_AUTH_ENDPOINT
            $url=$env:SIMPLE_AUTH_ENDPOINT+'/'+$fileName+'?'+$env:SIMPLE_AUTH_SAS_TOKEN
            Invoke-WebRequest $url -OutFile packages/fx-core/templates/plugins/resource/simpleauth/SimpleAuth.zip
        shell: pwsh

      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'MSFT-yiz'
          git config --global user.email 'yiz@microsoft.com'

      - name: release beta npm packages to npmjs.org
        if: ${{ github.event.inputs.stable }} == 'false'
        run: |
          npx lerna publish --no-private --preid=beta --dist-tag=beta prerelease --yes ${{ github.event.inputs.force }}

      - name: release stable npm packages to npmjs.org
        if: ${{ github.event.inputs.stable }} == 'true'
        run: |
          npx lerna publish --no-private --dist-tag=stable patch --yes ${{ github.event.inputs.force }}

      - name: pack vsix
        working-directory: ./packages/vscode-extension
        run: |
          npm install
          npx vsce package

      - name: release beta VSCode extension to github
        if: ${{ github.event.inputs.stable }} == 'false'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.CD_PAT }}"
          automatic_release_tag: "beta"
          prerelease: true
          files: |
            ./packages/**/*.vsix

      - name: release stable VSCode extension to github
        if: ${{ github.event.inputs.stable }} == 'true'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.CD_PAT }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            ./packages/**/*.vsix
