name: DotNet SDK CI

on:
  push:
    paths:
      - "packages/dotnet-sdk/**"
    branches: [main, dev, hotfix/**]
  pull_request:
    paths:
      - "packages/dotnet-sdk/**"
    branches: [main, dev, hotfix/**]
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/dotnet-sdk/

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Build
        run: dotnet build -c Release Microsoft.TeamsFx.sln
      - name: Test
        run: dotnet test Microsoft.TeamsFx.sln
