name: feature owner

on:
  pull_request:

jobs:
  feature-owner:
    if: ${{ github.event.pull_request.head.repo.full_name == 'OfficeDev/TeamsFx' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Skip forked repo
        run: |

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: assign-reviewer
        uses: LongOddCode/assign-reviewer@0.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: '["chagong", "XiaofuHuang", "hund030", "KennethBWSong"]'
          conscript: 0
          script: bash
          result: TELEMETRY_RESULT
          run: |
            line=`git diff -U0 origin/${{ github.base_ref }} | grep '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/)' | grep -i "telemetry" | wc -l`
            if [ "$line" -gt 0 ]; then
              echo '::set-output name=TELEMETRY_RESULT::true'
            fi
