name: FunctionExtension CI

on:
  push:
    path:
    - 'pacakges/function-extension/**'
    branches: [ main ]
  pull_request:
    path:
      - 'pacakges/function-extension/**'
    branches: [ main ]

defaults:
  run:
    working-directory: packages/function-extension/

jobs:  
  Function-Extension:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install Func CLI
      run: 
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb &&
        sudo apt-get update && sudo apt-get install azure-functions-core-tools-3
    - name: Build
      run: 
        dotnet build -c Release Microsoft.Azure.WebJobs.Extensions.TeamsFx.sln
    - name: Test
      env: 
        TeamsFx_BINDING_IntegrationTestSettings__ClientSecret: ${{secrets.FUNCTION_EXTENSION_CLIENT_SECRET}}
        TeamsFx_BINDING_IntegrationTestSettings__UnauthorizedAadAppClientSecret: ${{secrets.FUNCTION_EXTENSION_UNAUTHORIZED_AAD_APP_CLIENT_SECRET}}
        TeamsFx_BINDING_IntegrationTestSettings__AllowedAppClientSecret: ${{secrets.FUNCTION_EXTENSION_ALLOWED_APP_SECRET}}
      run:
        chmod +x "scripts/test.sh" && chmod +x "scripts/start_js_function.sh" && "scripts/test.sh"
