name: SimpleAuth CI

on:
  push:
    paths:
    - 'packages/simpleauth/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'packages/simpleauth/**'
    branches: [ main ]

defaults:
  run:
    working-directory: packages/simpleauth/

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: 
        dotnet build -c Release -p:WebDriverPlatform=linux64 Microsoft.TeamsFx.SimpleAuth.sln
    - name: Test
      env: 
        TEAMS_SIMPLE_AUTH_IntegrationTestSettings__AdminClientSecret: ${{secrets.SIMPLE_AUTH_TEST_ADMIN_CLIENT_SECRET}}
        TEAMS_SIMPLE_AUTH_IntegrationTestSettings__TestPassword: ${{secrets.SIMPLE_AUTH_TEST_PASSWORD}}
      run:
        chmod +x "scripts/test.sh" && "scripts/test.sh"
