name: publish to VSCode marketplace
run-name: Publish-${{ inputs.run_id }}-${{ github.ref_name }}-isPreview-${{ inputs.isPreview }}-${{ inputs.series }}
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Input the CD pipeline run ID to fetch the artifact"
        required: true
        default: ""
      isPreview:
        description: "Publish VSIX as a preview version(yes or no)"
        required: true
        default: "no"
      series:
        description: "release sprint series name"
        required: false
        default: ""

jobs:
  publish-to-vscode-marketplace:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      actions: read
      contents: write

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CD_PAT }}
          ref: ${{ github.head_ref }}

      - name: Download release artifacts
        uses: Legit-Labs/action-download-artifact@v2
        with:
          run_id: ${{ github.event.inputs.run_id }}
          name: release
          github_token: ${{ secrets.CD_PAT }}
          workflow: cd.yml
          path: .

      - name: get VSC beta tag
        if: ${{ github.event.inputs.isPreview != 'no' }}
        id: vsc_ver
        run: |
          VSC_VER=$(jq -c -r '.[]|select(.name == "ms-teams-vscode-extension")|.name+"@"+.version' versions.json)
          echo "-------------------" $VSC_VER
          echo "::set-output name=vsc_ver::$VSC_VER"

      - uses: mathieudutour/github-tag-action@v6.0
        if: ${{ github.event.inputs.isPreview != 'no' }}
        with:
          github_token: ${{ secrets.CD_PAT }}
          custom_tag: ${{ steps.vsc_ver.outputs.vsc_ver }}
          tag_prefix: ""

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PUBLISHER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PUBLISHER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PUBLISHER_AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: release preview to VSCode marketplace
        if: ${{ github.event.inputs.isPreview != 'no' }}
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            npx @vscode/vsce publish --pre-release --azure-credential --packagePath *.vsix --noVerify

      - name: release to VSCode marketplace
        if: ${{ github.event.inputs.isPreview == 'no' }}
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            npx @vscode/vsce publish --azure-credential --packagePath *.vsix --noVerify
